services:
  - type: web
    name: 1fi-assignment
    runtime: node
    plan: free
    buildCommand: npm ci && npx prisma generate && npx prisma db push --accept-data-loss && npm run db:seed && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
